# Generated by Django 6.0.3 on 2026-03-17 16:25

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('actor_type', models.TextField(choices=[('org', 'Org'), ('user', 'User'), ('system', 'System')])),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.TextField()),
                ('result', models.TextField(choices=[('ok', 'OK'), ('fail', 'Fail')])),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceRevocationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.UUIDField()),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('revoked_by_actor_type', models.TextField(choices=[('org', 'Org'), ('user', 'User'), ('system', 'System')])),
                ('revoked_by_actor_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'device_revocation_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeyUsageLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('device_key_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('challenge_id', models.UUIDField(blank=True, null=True)),
                ('action', models.TextField(choices=[('sign', 'Sign'), ('verify', 'Verify')])),
                ('result', models.TextField(choices=[('ok', 'OK'), ('fail', 'Fail')])),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'key_usage_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('status', models.TextField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='WaqaUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True, unique=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True, unique=True)),
                ('phone', models.TextField(blank=True, null=True, unique=True)),
                ('national_id_hmac', models.TextField(blank=True, null=True, unique=True)),
                ('status', models.TextField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password_hash', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
        migrations.AddField(
            model_name='device',
            name='app_instance_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_primary_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='platform',
            field=models.TextField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('desktop', 'Desktop')], default='unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='device',
            table='devices',
        ),
        migrations.CreateModel(
            name='OrganizationApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.TextField(unique=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='devices.organization')),
            ],
            options={
                'db_table': 'organization_api_keys',
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_user_ref', models.TextField()),
                ('status', models.TextField(choices=[('linked', 'Linked'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('unlinked', 'Unlinked')], default='linked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_users', to='devices.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_links', to='devices.waqauser')),
            ],
            options={
                'db_table': 'organization_users',
                'unique_together': {('organization', 'external_user_ref'), ('organization', 'user')},
            },
        ),
        migrations.CreateModel(
            name='VerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified_by_actor_type', models.TextField(blank=True, choices=[('primary', 'Primary'), ('delegate', 'Delegate')], null=True)),
                ('org_operation_ref', models.TextField()),
                ('operation_type', models.TextField()),
                ('operation_hash', models.TextField(blank=True, null=True)),
                ('operation_payload_encrypted', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('challenge_issued', 'Challenge Issued'), ('awaiting_user', 'Awaiting User'), ('verified', 'Verified'), ('denied', 'Denied'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending')),
                ('nonce', models.TextField(unique=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('decision_token_hash', models.TextField(blank=True, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='devices.device')),
                ('org_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='devices.organizationuser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='devices.organization')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sessions', to='devices.waqauser')),
            ],
            options={
                'db_table': 'verification_sessions',
                'unique_together': {('organization', 'org_operation_ref')},
            },
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.waqauser'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DeviceKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_purpose', models.TextField(choices=[('auth', 'Auth'), ('approval', 'Approval')])),
                ('algorithm', models.TextField(choices=[('ES256', 'ES256'), ('ES384', 'ES384'), ('RS256', 'RS256'), ('Ed25519', 'Ed25519')])),
                ('key_format', models.TextField(choices=[('COSE', 'COSE'), ('JWK', 'JWK'), ('PEM', 'PEM'), ('RAW', 'RAW')])),
                ('public_key', models.TextField()),
                ('attestation_type', models.TextField(blank=True, null=True)),
                ('attestation_data', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_keys', to='devices.organization')),
            ],
            options={
                'db_table': 'device_keys',
                'unique_together': {('device', 'organization', 'key_purpose')},
            },
        ),
        migrations.CreateModel(
            name='VerificationChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_bytes', models.TextField()),
                ('attempt_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='devices.verificationsession')),
            ],
            options={
                'db_table': 'verification_challenges',
                'unique_together': {('session', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='DelegatedAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_via', models.TextField(choices=[('qr', 'QR'), ('otp', 'OTP')])),
                ('status', models.TextField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('delegate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegated_from', to='devices.waqauser')),
                ('primary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegated_to', to='devices.waqauser')),
            ],
            options={
                'db_table': 'delegated_access',
                'unique_together': {('primary_user', 'delegate_user')},
            },
        ),
    ]
