# Generated by Django 4.2.11 on 2026-04-27 15:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_endpoints', '0001_initial'),
        ('accounts_endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRevocationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.UUIDField()),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('revoked_by_actor_type', models.CharField(choices=[('org', 'Org'), ('user', 'User'), ('system', 'System')], max_length=10)),
                ('revoked_by_actor_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'device_revocation_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('desktop', 'Desktop')], max_length=20)),
                ('app_instance_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary_device', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts_endpoints.waqauser')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_purpose', models.CharField(choices=[('auth', 'Auth'), ('approval', 'Approval')], max_length=20)),
                ('algorithm', models.CharField(choices=[('ES256', 'ES256'), ('ES384', 'ES384'), ('RS256', 'RS256'), ('Ed25519', 'Ed25519')], max_length=20)),
                ('key_format', models.CharField(choices=[('COSE', 'COSE'), ('JWK', 'JWK'), ('PEM', 'PEM'), ('RAW', 'RAW')], max_length=10)),
                ('public_key', models.TextField()),
                ('attestation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('attestation_data', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='devices_endpoints.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_keys', to='organization_endpoints.organization')),
            ],
            options={
                'db_table': 'device_keys',
                'unique_together': {('device', 'organization', 'key_purpose')},
            },
        ),
    ]
