# Generated by Django 6.0.5 on 2026-05-19 23:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_endpoints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('desktop', 'Desktop')], max_length=20)),
                ('app_instance_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_primary_device', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_purpose', models.CharField(choices=[('auth', 'Auth'), ('approval', 'Approval')], max_length=20)),
                ('algorithm', models.CharField(choices=[('ES256', 'ES256'), ('ES384', 'ES384'), ('RS256', 'RS256')], max_length=20)),
                ('key_format', models.CharField(choices=[('COSE', 'COSE'), ('JWK', 'JWK'), ('PEM', 'PEM'), ('X509', 'X509')], max_length=10)),
                ('public_key', models.TextField()),
                ('attestation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('attestation_data', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='devices_endpoints.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_keys', to='organization_endpoints.organization')),
            ],
            options={
                'db_table': 'device_keys',
            },
        ),
        migrations.CreateModel(
            name='DeviceRevocationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.UUIDField()),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('revoked_by_actor_type', models.CharField(choices=[('org', 'Organization'), ('user', 'User'), ('system', 'System')], max_length=10)),
                ('revoked_by_actor_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'device_revocation_logs',
                'indexes': [models.Index(fields=['device_id'], name='device_revo_device__bb0d17_idx'), models.Index(fields=['user_id'], name='device_revo_user_id_2f3a21_idx'), models.Index(fields=['created_at'], name='device_revo_created_6cee8c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'is_active'], name='devices_user_id_095ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['app_instance_id'], name='devices_app_ins_b0d005_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_device', True)), fields=('user',), name='unique_primary_device_per_user'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user', 'app_instance_id'), name='unique_app_instance_per_user'),
        ),
        migrations.AddIndex(
            model_name='devicekey',
            index=models.Index(fields=['device', 'is_active'], name='device_keys_device__89c8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='devicekey',
            index=models.Index(fields=['organization', 'is_active'], name='device_keys_organiz_cd6013_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicekey',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('device', 'organization', 'key_purpose'), name='unique_active_device_key_per_scope'),
        ),
    ]
