# Generated by Django 6.0.5 on 2026-05-19 23:45

import accounts_endpoints.managers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('national_id_hmac', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts',
            },
            managers=[
                ('objects', accounts_endpoints.managers.AccountUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('national_id_hmac', models.CharField(db_index=True, max_length=64)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('display_name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('identity_verified', 'Identity Verified'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registration_sessions',
            },
        ),
        migrations.CreateModel(
            name='UserDelegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delegation_method', models.CharField(choices=[('qr', 'QR'), ('otp', 'OTP')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegated_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('owner_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_delegations',
            },
        ),
        migrations.AddIndex(
            model_name='accountuser',
            index=models.Index(fields=['status'], name='accounts_status_8b566b_idx'),
        ),
        migrations.AddIndex(
            model_name='accountuser',
            index=models.Index(fields=['national_id_hmac'], name='accounts_nationa_16d7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationsession',
            index=models.Index(fields=['status', 'expires_at'], name='registratio_status_3e4ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationsession',
            index=models.Index(fields=['national_id_hmac', 'status'], name='registratio_nationa_c1d10e_idx'),
        ),
        migrations.AddConstraint(
            model_name='registrationsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'identity_verified'])), fields=('national_id_hmac',), name='regsession_one_active_per_national_id'),
        ),
        migrations.AddIndex(
            model_name='userdelegation',
            index=models.Index(fields=['owner_account', 'status'], name='user_delega_owner_a_a6fbbf_idx'),
        ),
        migrations.AddIndex(
            model_name='userdelegation',
            index=models.Index(fields=['delegated_account', 'status'], name='user_delega_delegat_c3374d_idx'),
        ),
        migrations.AddConstraint(
            model_name='userdelegation',
            constraint=models.CheckConstraint(condition=models.Q(('owner_account', models.F('delegated_account'))), name='udel_no_self_delegation'),
        ),
        migrations.AddConstraint(
            model_name='userdelegation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('owner_account', 'delegated_account'), name='udel_unique_active'),
        ),
    ]
