<<<<<<< HEAD
# Generated by Django 4.2.11 on 2026-04-16 14:55
=======
# Generated by Django 4.2.11 on 2026-04-27 15:35
>>>>>>> 3e8058b105db20eaa85db9b5f30bd7e1705edb71

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='RegistrationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('national_id', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('nafath_verified', 'Nafath Verified'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> 3e8058b105db20eaa85db9b5f30bd7e1705edb71
            name='WaqaUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('national_id_hmac', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password_hash', models.TextField()),
            ],
            options={
<<<<<<< HEAD
                'db_table': 'waqaa_users',
=======
                'db_table': 'users',
                'indexes': [models.Index(fields=['username'], name='users_usernam_baeb4b_idx'), models.Index(fields=['phone'], name='users_phone_af6883_idx'), models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['national_id_hmac'], name='users_nationa_de9002_idx'), models.Index(fields=['status'], name='users_status_9ca66f_idx')],
>>>>>>> 3e8058b105db20eaa85db9b5f30bd7e1705edb71
            },
        ),
        migrations.CreateModel(
            name='DelegatedAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_via', models.CharField(choices=[('qr', 'QR'), ('otp', 'OTP')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('delegate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegated_from', to='accounts_endpoints.waqauser')),
                ('primary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegated_to', to='accounts_endpoints.waqauser')),
            ],
            options={
                'db_table': 'delegated_access',
            },
        ),
<<<<<<< HEAD
=======
        migrations.AddConstraint(
            model_name='delegatedaccess',
            constraint=models.UniqueConstraint(fields=('primary_user', 'delegate_user'), name='unique_primary_delegate_pair'),
        ),
>>>>>>> 3e8058b105db20eaa85db9b5f30bd7e1705edb71
    ]
