# Generated by Django 6.0.5 on 2026-05-29 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delegation_codes',
                'indexes': [models.Index(fields=['code'], name='delegation__code_f38a6b_idx'), models.Index(fields=['expires_at'], name='delegation__expires_e2a562_idx')],
            },
        ),
    ]
