# Generated by Django 6.0.5 on 2026-05-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_endpoints', '0002_delegationcode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userdelegation',
            name='udel_no_self_delegation',
        ),
        migrations.RemoveConstraint(
            model_name='userdelegation',
            name='udel_unique_active',
        ),
        migrations.AddConstraint(
            model_name='userdelegation',
            constraint=models.CheckConstraint(condition=models.Q(('owner_account', models.F('delegated_account')), _negated=True), name='udel_no_self_delegation'),
        ),
        migrations.AddConstraint(
            model_name='userdelegation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), _negated=True), fields=('owner_account', 'delegated_account'), name='udel_unique_active'),
        ),
    ]
