<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-05-20 04:52
=======
# Generated by Django 6.0.5 on 2026-05-19 23:45
>>>>>>> e66e874ba93f487373079a32db1325e27f0922a9

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices_endpoints', '0001_initial'),
        ('organization_endpoints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('actor_type', models.CharField(choices=[('org', 'Organization'), ('user', 'User'), ('system', 'System')], max_length=10)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('ok', 'OK'), ('fail', 'Fail')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'created_at'], name='idx_audit_org_created'), models.Index(fields=['session_id', 'created_at'], name='idx_audit_session_created')],
            },
        ),
        migrations.CreateModel(
            name='KeyUsageLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('device_key_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('challenge_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('sign', 'Sign'), ('verify', 'Verify')], max_length=100)),
                ('result', models.CharField(choices=[('ok', 'OK'), ('fail', 'Fail')], max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'key_usage_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'created_at'], name='idx_keylog_org_created'), models.Index(fields=['device_id', 'created_at'], name='idx_keylog_device_created'), models.Index(fields=['session_id'], name='idx_keylog_session')],
            },
        ),
        migrations.CreateModel(
            name='VerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified_by_actor_type', models.CharField(blank=True, choices=[('primary', 'Primary'), ('delegate', 'Delegate')], max_length=10, null=True)),
                ('org_operation_ref', models.CharField(max_length=255)),
                ('operation_type', models.CharField(choices=[('login', 'Login'), ('update_profile', 'Update Profile'), ('add_delegate', 'Add Delegate'), ('remove_delegate', 'Remove Delegate'), ('transfer', 'Transfer')], max_length=32)),
                ('operation_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('operation_payload_encrypted', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('challenge_issued', 'Challenge Issued'), ('awaiting_user', 'Awaiting User'), ('verified', 'Verified'), ('denied', 'Denied'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('nonce', models.CharField(max_length=64, unique=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('decision_token_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_sessions', to='devices_endpoints.device')),
                ('org_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_sessions', to='organization_endpoints.organizationuser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_sessions', to='organization_endpoints.organization')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_bytes', models.TextField()),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='verification_endpoint.verificationsession')),
            ],
            options={
                'db_table': 'verification_challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='verificationsession',
            index=models.Index(fields=['status', 'expires_at'], name='idx_vs_status_expires'),
        ),
        migrations.AddIndex(
            model_name='verificationsession',
            index=models.Index(fields=['organization', 'status'], name='idx_vs_org_status'),
        ),
        migrations.AddIndex(
            model_name='verificationsession',
            index=models.Index(fields=['org_user', 'status'], name='idx_vs_orguser_status'),
        ),
        migrations.AddConstraint(
            model_name='verificationsession',
            constraint=models.UniqueConstraint(fields=('organization', 'org_operation_ref'), name='uq_verification_session_org_operation_ref'),
        ),
        migrations.AddIndex(
            model_name='verificationchallenge',
            index=models.Index(fields=['session', 'is_active', 'is_used'], name='idx_challenge_active_used'),
        ),
        migrations.AddIndex(
            model_name='verificationchallenge',
            index=models.Index(fields=['expires_at'], name='idx_challenge_expires'),
        ),
        migrations.AddConstraint(
            model_name='verificationchallenge',
            constraint=models.UniqueConstraint(fields=('session', 'attempt_number'), name='uq_challenge_session_attempt'),
        ),
    ]
