# Generated by Django 4.2.11 on 2026-04-16 14:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_endpoints', '0001_initial'),
        ('devices_endpoints', '0001_initial'),
        ('accounts_endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('actor_type', models.TextField(choices=[('org', 'Org'), ('user', 'User'), ('system', 'System')])),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.TextField()),
                ('result', models.TextField(choices=[('ok', 'OK'), ('fail', 'Fail')])),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeyUsageLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('device_key_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('challenge_id', models.UUIDField(blank=True, null=True)),
                ('action', models.TextField(choices=[('sign', 'Sign'), ('verify', 'Verify')])),
                ('result', models.TextField(choices=[('ok', 'OK'), ('fail', 'Fail')])),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'key_usage_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified_by_actor_type', models.CharField(blank=True, choices=[('primary', 'Primary'), ('delegate', 'Delegate')], max_length=15, null=True)),
                ('org_operation_ref', models.CharField(max_length=255)),
                ('operation_type', models.CharField(max_length=100)),
                ('operation_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('operation_payload_encrypted', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('challenge_issued', 'Challenge Issued'), ('awaiting_user', 'Awaiting User'), ('verified', 'Verified'), ('denied', 'Denied'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('nonce', models.CharField(max_length=64, unique=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('decision_token_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='devices_endpoints.device')),
                ('org_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='organization_endpoints.organizationuser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='organization_endpoints.organization')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sessions', to='accounts_endpoints.waqauser')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_bytes', models.TextField()),
                ('attempt_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='verification_endpoint.verificationsession')),
            ],
            options={
                'db_table': 'verification_challenges',
                'unique_together': {('session', 'attempt_number')},
            },
        ),
    ]
