# Generated by Django 4.2.11 on 2026-04-27 15:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to='accounts_endpoints.waqauser')),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_provider', models.CharField(choices=[('internal', 'Internal'), ('google', 'Google'), ('apple', 'Apple')], max_length=50)),
                ('external_user_ref', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('linked', 'Linked'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('unlinked', 'Unlinked')], db_index=True, default='linked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], db_index=True, default='member', max_length=20)),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_users', to='accounts_endpoints.waqauser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_users', to='organization_endpoints.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_links', to='accounts_endpoints.waqauser')),
            ],
            options={
                'db_table': 'organization_users',
                'indexes': [models.Index(fields=['organization', 'user'], name='organizatio_organiz_a29000_idx'), models.Index(fields=['external_user_ref'], name='organizatio_externa_253e2a_idx'), models.Index(fields=['user'], name='organizatio_user_id_7f8cc2_idx')],
                'unique_together': {('organization', 'user'), ('organization', 'external_user_ref')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.IntegerField(default=10)),
                ('total_requests', models.IntegerField(default=0)),
                ('allowed_ips', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), blank=True, null=True, size=None)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to='accounts_endpoints.waqauser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organization_endpoints.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_api_keys', to='accounts_endpoints.waqauser')),
            ],
            options={
                'db_table': 'organization_api_keys',
                'indexes': [models.Index(fields=['organization'], name='organizatio_organiz_11b24b_idx'), models.Index(fields=['key_hash'], name='organizatio_key_has_f2b551_idx'), models.Index(fields=['created_by'], name='organizatio_created_25d03e_idx'), models.Index(fields=['is_active'], name='organizatio_is_acti_aaf450_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='organizationapikey',
            constraint=models.CheckConstraint(check=models.Q(('scopes', []), _negated=True), name='scopes_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='organizationapikey',
            constraint=models.UniqueConstraint(condition=models.Q(('label', None), _negated=True), fields=('organization', 'label'), name='unique_label_per_org'),
        ),
    ]
