# Generated by Django 4.2.11 on 2026-04-16 14:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('status', models.TextField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.TextField(unique=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organization_endpoints.organization')),
            ],
            options={
                'db_table': 'organization_api_keys',
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_user_ref', models.TextField()),
                ('status', models.TextField(choices=[('linked', 'Linked'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('unlinked', 'Unlinked')], default='linked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_users', to='organization_endpoints.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_links', to='accounts_endpoints.waqauser')),
            ],
            options={
                'db_table': 'organization_users',
                'unique_together': {('organization', 'user'), ('organization', 'external_user_ref')},
            },
        ),
    ]
