# Generated by Django 6.0.5 on 2026-05-19 23:45

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(max_length=128, unique=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('allowed_ips', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organization_endpoints.organization')),
            ],
            options={
                'db_table': 'organization_api_keys',
                'indexes': [models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_e658d3_idx'), models.Index(fields=['key_hash'], name='organizatio_key_has_f2b551_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('scopes', []), _negated=True), name='orgapikey_scopes_not_empty'), models.UniqueConstraint(condition=models.Q(('label', None), _negated=True), fields=('organization', 'label'), name='orgapikey_unique_label_per_org')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_provider', models.CharField(choices=[('internal', 'Internal'), ('google', 'Google'), ('apple', 'Apple')], default='internal', max_length=50)),
                ('external_user_ref', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], db_index=True, default='member', max_length=20)),
                ('status', models.CharField(choices=[('linked', 'Linked'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('unlinked', 'Unlinked')], db_index=True, default='linked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_users', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_users', to='organization_endpoints.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_users',
                'indexes': [models.Index(fields=['organization', 'user'], name='organizatio_organiz_a29000_idx'), models.Index(fields=['external_user_ref'], name='organizatio_externa_253e2a_idx')],
                'unique_together': {('organization', 'external_user_ref'), ('organization', 'user')},
            },
        ),
    ]
